# Generated by Django 3.1.2 on 2021-07-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=30)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udhaar.party')),
            ],
        ),
    ]
