# Generated by Django 3.1.2 on 2021-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
