# Generated by Django 3.1.2 on 2021-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhaar', '0003_auto_20210725_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='total',
        ),
        migrations.AddField(
            model_name='party',
            name='Balance',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
